name: eco_avanzado
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pie_chart: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
  - assets/img/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/pantalla_home.png"